version: '2.17.2'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_started
    command: nginx -g 'daemon off;'

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    command: "sh ./start-app.sh"

  database:
    image: postgres:13
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=task_08_04_2024
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
